# Generated by Django 4.1 on 2022-08-22 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('identification', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
                ('save_user', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
